### ISSUE TITLE
unable to build in cygwin x86 using GNU make 4.1

### ISSUE THREAD

**Issue by anjanb** [apangin/jattach#1]
Tried building on windows 7 Enterprise using cygwin with GNU make 4.1. Got below errors

c:\work\java\heapDump\jattach-master>make
mkdir -p build
gcc -O2 -o build/jattach src/jattach.c
make: gcc: Command not found
Makefile:4: recipe for target 'build/jattach' failed
make: *** [build/jattach] Error 127

c:\work\java\heapDump\jattach-master>make --version
GNU Make 4.1
Built for i686-pc-cygwin
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

c:\work\java\heapDump\jattach-master>

**Comment by apangin** [comment]
Added jattach_windows that builds with MSVC++.

**Comment by anjanb** [comment]
cool. thank you.
