### ISSUE TITLE
Attaching to containerized JVM

### ISSUE THREAD

**Issue by goldshtn** [apangin/jattach#10]
Attaching to a JVM running in a container requires a bit of trickery. Simply running `jattach $PID` doesn't work, of course, because jattach tries to write to the current directory of the containerized process, which is in a different mount namespace, and everything goes downhill from there.

However, assuming that /tmp is mapped to the same directory on the host and the container (e.g. using `docker -v /tmp:/tmp`), the following works:

```
$ sudo nsenter -t $PID -m touch /proc/1/cwd/.attach_pid1
$ sudo kill -SIGQUIT $PID
$ sudo jattach 1 <command>
```

The /tmp mapping is needed because the UNIX domain socket is in /tmp/.java_pid1. If the process in the container is not running as root, sudo needs to use the proper user id (because IIRC the JVM checks the other side of the socket to see that it's the same uid).

Can we somehow automate this process within the tool? E.g. if jattach calls setns to enter the target's mount namespace, and parses /proc/$PID/status to figure out the proper PID (in the container's terms) for formatting the .attach_pid and .java_pid paths, then everything would just work, I think. We wouldn't even need the /tmp volume mapping.

The alternative is to tell people to put jattach inside the container, but that's not always possible.

**Comment by apangin** [comment]
Makes sense.
BTW, if the target JVM is launched with `-XX:+StartAttachListener`, there is no need to create `.attach_pid` file and to send SIGQUIT (JVM is already listening to a socket for incoming connections).
