### ISSUE TITLE
Could not create remote thread (error code = 8)

### ISSUE THREAD

**Issue by lesniakbj** [apangin/jattach#19]
I am trying to troubleshoot a Java Process for one of our legacy systems, one that doesn't run out of memory, but consistently uses almost all of the system's memory; and it appears that this system is Running on Windows XP.

When I attempt to run
`jattach <PID> dumpheap \heapdump\heap.bin`

I get the titled error. Some cursory research shows that the call 
` HANDLE hThread = CreateRemoteThread(hProcess, NULL, 0, code, data, 0, NULL);`

is what is causing the issues. Appears to be related to something with the process sessions on older machines vs newer versions of windows (https://stackoverflow.com/questions/40429629/createremotethread-failing-with-error-not-enough-memory). Then again, it could be something else completely. 

Should I be running the command host as administrator, or will that not help in this situation?

As a note, I would be willing to work on and submit a PR for this if there ends up being any sort of issue and not user error, but I am mostly unfamiliar with C/Windows APIs. If we can figure out what the issue is, and the direction needed for a fix, I could probably submit something.

**Comment by lesniakbj** [comment]
I saw this at an offsite location, but will see if I can reproduce it locally (and consistently). I'll get back to you after I try.

**Comment by apangin** [comment]
I'm closing the issue, as it doesn't seem to require further actions right now.
Feel free to reopen when you have more information about reproducing the problem.
