### ISSUE TITLE
Unable to build on Windows using Visual Studio 2010

### ISSUE THREAD

**Issue by anjanb** [apangin/jattach#2]
Tried to create a Windows console project and added the jattach.c code to the project. 

Multiple errors.
Doesn't know sys/socket.h, un.h and unistd.h.

What are the equivalent of these in windows ?

Can you #ifndef __WINDOWS conditionally include files for windows and linux ?

**Comment by apangin** [comment]
Currently implementation is only for Linux and BSD. This does not work on Windows, since there are no UNIX domain soocket support. Dynamic Attach requires different implementation on Windows, I'll do it shortly.

**Comment by anjanb** [comment]
Hi Andrei,

  Thank you.

BR,
~A

**Comment by apangin** [comment]
Added Windows implementation.

**Comment by anjanb** [comment]
hi andrei,

  thank you very much.

  I will build it tomorrow and let you know how it goes.

BR,
~A
