### ISSUE TITLE
Installation on Linux CentOS

### ISSUE THREAD

**Issue by martinkrc** [apangin/jattach#24]
Hello,
Is it possible to install jattach on CentOS? Colleagues are telling me that it is not. The exact system is:
Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-957.12.1.el7.x86_64

Thanks,
Martin

**Comment by apangin** [comment]
`jattach` is a single self-contained binary which works on nearly all Linux flavors with glibc.
And certainly it works on CentOS 7 x64.
It requires no installation, just copy the binary from [releases](https://github.com/apangin/jattach/releases) page or build it on your own from the sources with `make` command.

**Comment by martinkrc** [comment]
You're right, it actually works fine on CentOS, tested now. Thanks!
