### ISSUE TITLE
Unable to call jattach from c#/batch script

### ISSUE THREAD

**Issue by Nikesht** [apangin/jattach#27]
Hi,
I am trying to test the scenario where i want my c# code to run jattach for given process. 
I am getting  either error code 87, or
 it just hung, on cancellation i can see following statement:
"Connected to remote process
Response code = "

Let me know if there is some work around to this problem.

**Comment by apangin** [comment]
Why do you think the problem is in jattach?
Does jattach work when you run it manually?

**Comment by apangin** [comment]
Does not seem to be a jattach issue.
Closing the issue in the absense of further details.
