### ISSUE TITLE
Trouble attaching to JVM on both Windows and Linux

### ISSUE THREAD

**Issue by quickiwiki** [apangin/jattach#29]
Unable to attach to an OpenJDK 8 64 on both Windows and Linux
On Linux Ubuntu 19.10  JVM responds with the following:

Connected to remote JVM
Response code = -1

If I try to attach on Windows 10 the Java process just quits.

**Comment by deadok22** [comment]
Hi @quickiwiki!

It seems jattach attaches to your JVM successfully, but the command itself returns `-1`. Could you share more details? What's the command? What's the output of `java -version`?

**Comment by quickiwiki** [comment]
On Windows:
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

Command:  .\jattach.exe 24736 load D:\SRC\agent\agent.dll
Output:
Connected to remote process
Attach is not supported by the target process (error code = -1073741819)

**Comment by apangin** [comment]
There's one argument missing in your command line.
`load` command requires another argument after the library name:
- `true`, if the given library path is absolute (your case);
- `false`, if the short library name is specified instead of full path.

See https://github.com/apangin/jattach#load-jvmti-agent

**Comment by quickiwiki** [comment]
The problem remains the same even if I add true to the command line arguments 
 .\jattach.exe 29656 load true D:\SRC\agent\agent.dll
Connected to remote process
Attach is not supported by the target process (error code = -1073741819)

**Comment by quickiwiki** [comment]
Tried the 'true' argument on Ubuntu 19.10

openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~19.10-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

~/src/jattach/build$ ./jattach 22825 load /home/user/agent/libagent.so true

Connected to remote JVM
Response code = -1

**Comment by deadok22** [comment]
Just to reduce the potential problem space a little bit, could you run a simpler command using jattach? It could be there's something wrong with the .so

**Comment by quickiwiki** [comment]
sudo ./jattach 3572 jcmd "help -all" worked for me

but the aforementioned agent lib is a simple test agent with Agent_OnLoad and Agent_OnUnload functions

**Comment by deadok22** [comment]
Thanks! So it seems the issue you're experiencing on Linux is not jattach-specific. I suggest you try loading an agent binary that's known to be working and then dig into any file permissions/mode/ownership or agent-specific issues you may find.

I don't have a Windows machine at hand to try reproducing the other issue, unfortunately.

**Comment by quickiwiki** [comment]
> Thanks! So it seems the issue you're experiencing on Linux is not jattach-specific. I suggest you try loading an agent binary that's known to be working and then dig into any file permissions/mode/ownership or agent-specific issues you may find.
> 
> I don't have a Windows machine at hand to try reproducing the other issue, unfortunately.

As I have previously mentioned the lib agent I am trying to use with jattach works fine, e.g:

java -agentpath:/home/user/agent/libagent.so -jar boot2-0.0.1-SNAPSHOT.jar 
I'm a native Agent....
Got environment
Set event callbacks....
Set notification mode....


What working agent would you suggest for me to try?

**Comment by apangin** [comment]
> agent lib is a simple test agent with Agent_OnLoad and Agent_OnUnload functions

That's the problem. In order to support dynamic attach, the agent MUST export `Agent_OnAttach`

**Comment by quickiwiki** [comment]
> > agent lib is a simple test agent with Agent_OnLoad and Agent_OnUnload functions
> 
> That's the problem. In order to support dynamic attach, the agent MUST export `Agent_OnAttach`
Thanks. WIll try it with the sample native agent. Btw, is it possible to attach a java agent using jattach provided that it has agentmain and premain entry points?

**Comment by apangin** [comment]
Yes, Java Agent is a special case of JVM TI agent.

JDK has a built-in native agent "instrument" (libinstrument.so) which is responsible for loading Java Agents.

To load Java Agent `agent.jar` with arguments `my_agent_args`, invoke
```
jattach <pid> load instrument false "/path/to/agent.jar=my_agent_args"
```

**Comment by quickiwiki** [comment]
> Yes, Java Agent is a special case of JVM TI agent.
> 
> JDK has a built-in native agent "instrument" (libinstrument.so) which is responsible for loading Java Agents.
> 
> To load Java Agent `agent.jar` with arguments `my_agent_args`, invoke
> 
> ```
> jattach <pid> load instrument false "/path/to/agent.jar=my_agent_args"
> ```

Thanks a lot! I will try straight away

**Comment by quickiwiki** [comment]
> 
> 
> Yes, Java Agent is a special case of JVM TI agent.
> 
> JDK has a built-in native agent "instrument" (libinstrument.so) which is responsible for loading Java Agents.
> 
> To load Java Agent `agent.jar` with arguments `my_agent_args`, invoke
> 
> ```
> jattach <pid> load instrument false "/path/to/agent.jar=my_agent_args"
> ```

It works on Linux.
On WIndows I still get this
Attach is not supported by the target process (error code = -1073741819)

**Comment by apangin** [comment]
-1073741819 (0xc0000005) is EXCEPTION_ACCESS_VIOLATION - Windows name for Segmentation Fault.

Does this happen only with your agent, or with other basic commands like `jattach PID threaddump` ?

**Comment by quickiwiki** [comment]
Unfortunately  I still get the same result. The JVM quits and jattach outputs the following:

PS D:\SRC\jattach\x64\Debug>  .\jattach.exe 1324 threaddump
Connected to remote process
Attach is not supported by the target process (error code = -1073741819)

**Comment by apangin** [comment]
Have you built `jattach.exe` yourself?
What about the "official" binary at https://github.com/apangin/jattach/releases ?

**Comment by apangin** [comment]
Closing the issue, as the original question is answered, and there is no further feedback from the question author.
