### ISSUE TITLE
Get Error "Could not open process (error code = 5)" on OpenJDK 64-bit JVM

### ISSUE THREAD

**Issue by anjanb** [apangin/jattach#3]
I"m using OpenJDK 64-bit from zulu on windows 7. When I run the command(jattach 16092 dumpheap c:\temp\rumengineHeap.bin), I get the error "Could not open process (error code = 5)". What does this mean ? I ran the jattach process from a console (cmd.exe) that ran as administrator.

**Comment by apangin** [comment]
Error code 5 means "Access is denied". Do you run jattach on the same machine you've compiled it on? There is a known issue with PROCESS_ALL_ACCESS constant that may have different value on different OS versions. Try to narrow the requested set of access rights for OpenProcess(). Try also running the utility under the same user as Java process owner and make sure PID is correct.

**Comment by anjanb** [comment]
I run jattach on the same machine compiled on. The target JVM is a 64-bit process running as a child of a windows service -- user is SYSTEM. Are you suggesting that I run jattach also as a child of a service so that it can run as SYSTEM ?

**Comment by apangin** [comment]
Ah, you run Java under SYSTEM account. This makes difference.
I think I know how to deal with that. The fix will follow.

**Comment by apangin** [comment]
Just committed the fix to adjust privileges if the target process is run by different user. Please let me know if it solves the problem.
