### ISSUE TITLE
Statistic on Memory Heap Usage

### ISSUE THREAD

**Issue by siruslan** [apangin/jattach#31]
First of all, thank you for creating this useful tool! It's simple and yet powerful. 

I'm trying to figure out how to get USED heap RAM of JVM which is running inside a docker container. If java process is not running in a docker container than we can 
```
start="ManagementAgent.start jmxremote.port=$port jmxremote.rmi.port=$port jmxremote.ssl=false jmxremote.authenticate=false"
jattach $pid jcmd "$start"
```
and then connect via JMX with the following code 
```
JMXConnector c = JMXConnectorFactory.newJMXConnector(createConnectionURL(host, port), null);
c.connect();
MBeanServerConnection mbsc = c.getMBeanServerConnection();
MemoryMXBean mem = ManagementFactory.getPlatformMXBean(mbsc, MemoryMXBean.class);
MemoryUsage heap = mem.getHeapMemoryUsage();
MemoryUsage nonHeap = mem.getNonHeapMemoryUsage();
```

However, with docker it does not work as we have to open jmx port at the start of the container which is not possible in our case. We run inspection / memory usage analysis on the host machine and can't stop/start containers for this operation. 

Maybe _datadump_ command can provide a summary about used heap memory, but it seems like this command does not provide any information...
```
jattach <pid> datadump
Connected to remote JVM
Response code = 0 
```

What can you advise? Is there any way to get JMX information via jattach without the need to open JMX port in a docker container? 

Thanks

**Comment by deadok22** [comment]
Hi @siruslan! Have a look at `jattach $pid jcmd GC.heap_info`. It's not exactly the same thing, but it may suit your needs.

**Comment by deadok22** [comment]
One other option you may want to look into is using hsperfdata file and jstat command.

**Comment by siruslan** [comment]
Unfortunately the both options do not provide the same info as MXBean. I managed to connect to java process via internal IP without exposing the JMX port. There is some bash logic that helps.   

```
function getCtIP {
  local pid="$1"

  if [[ -z "$pid" ]]; then
    echo "Missing host PID argument."
    exit 1
  fi

  if [ "$pid" -eq "1" ]; then
    echo "Unable to resolve host PID to a container name."
    exit 2
  fi

  # ps returns values potentially padded with spaces, so we pass them as they are without quoting.
  local parentPid="$(ps -o ppid= -p $pid)"
  local ct="$(ps -o args= -f -p $parentPid | grep containerd-shim)"
  m="moby/"
  if [[ -n "$ct" ]]; then
    local ctid=$(echo ${ct#*$m} | cut -d' ' -f1)
    docker inspect $ctid | grep IPAddress | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b"
  else
    getCtIP "$parentPid" $2
  fi
}
```

**Comment by krisnik** [comment]
Hi, I did also observe that `datadump` command does not output anything.

```
jattach <pid> datadump
Connected to remote JVM
Response code = 0 
```

Are there any options that I'm missing here?

**Comment by apangin** [comment]
@krisnik The result of `datadump` command is printed to the standard output of the target JVM process (by design).
If you want to see output in `jattach` console, use `threaddump` and `jcmd GC.heap_info` commands instead.

**Comment by jumarko** [comment]
> @krisnik The result of `datadump` command is printed to the standard output of the target JVM process (by design). If you want to see output in `jattach` console, use `threaddump` and `jcmd GC.heap_info` commands instead.

@apangin it would be great to mention this in the README ;).
