### ISSUE TITLE
Unable to take threaddump during the issue

### ISSUE THREAD

**Issue by neerajtiwar** [apangin/jattach#34]
Hi,

I am using jattach inside docker container, I am able to take thread dump when my application or JVM is running fine, but when the JVM has any issue like threads choked or memory leak, I mean to say unresponsive. jattach is giving following error:

Could not start attach mechanism: No such file or directory

**Comment by apangin** [comment]
This is kind of expected. Dynamic Attach mechanism requires cooperation from the JVM. If the JVM is stuck, the tools depending on Dynamic Attach, will not work.

See [this answer](https://stackoverflow.com/a/35963059/3448419) for the explanation.
