### ISSUE TITLE
getting Response code = -1 when trying to load agent

### ISSUE THREAD

**Issue by nevotz** [apangin/jattach#35]
when running jattach pid load agent.so i get :
Connected to remote JVM
Response code = -1

**Comment by deadok22** [comment]
@nevotz please see other similar issues - it could be your very problem was faced by somebody else before. 

If that doesn't help, please share more details about your set up. What agent do you load, what are its dependencies (run ldd agent.so)? Is the path available to the target JVM? Does its user have permissions to read the .so file?

**Comment by apangin** [comment]
`Response code = -1` means that the problem is in the agent library, not in jattach.
jattach was able to connect to the JVM, but JVM could not load the agent library. See #29, #30.

**Comment by nevotz** [comment]
after running this commnad: nm -D lightrun_agent.so | grep "T Agent_OnLoad"
00000000000e7780 T Agent_OnLoad

**Comment by apangin** [comment]
There should be `Agent_OnAttach`, not `Agent_OnLoad`

**Comment by nevotz** [comment]
nm -D lightrun_agent.so | grep "T Agent_OnAttach"
return nothing .
i will ask the agent programmer to add it i guess

thank you so much for your quick response .
i really appreciate it
