### ISSUE TITLE
JNI implementation of jattach

### ISSUE THREAD

**Issue by TheOiseth** [apangin/jattach#37]
I adapted the code for jni and created a lightweight library that implements jattach functions in a single jar file for Linux, Mac and Windows.
https://github.com/TheOiseth/jni-jattach

**Comment by apangin** [comment]
Good. It worth mention that attaching from Java to Java is also possible with

- [Attach API](https://docs.oracle.com/en/java/javase/11/docs/api/jdk.attach/com/sun/tools/attach/VirtualMachine.html)
- [ByteBuddyAgent](https://javadoc.io/doc/net.bytebuddy/byte-buddy-agent/latest/net/bytebuddy/agent/ByteBuddyAgent.html)

**Comment by apangin** [comment]
Anything else needed from jattach regarding this issue, or I can just close it?

**Comment by TheOiseth** [comment]
Yes, you can close it
