### ISSUE TITLE
Error "Could not create remote thread (error code = 5)"  on Oracle 64-bit JVM

### ISSUE THREAD

**Issue by anjanb** [apangin/jattach#4]
The JVM that I tried to dump heap was Oracle 64-JVM on windows 7. Unlike on the 64-bit OpenJDK(zulu), this one give a different error code. The user running jattach and the JVM are both the same. Notice this time the error is not "Could not open process", it is "could not create remote thread".

**Comment by apangin** [comment]
I could not reproduce the issue. Please check if the problem persists after calling [`enable_debug_privileges()`](https://github.com/apangin/jattach/blob/master/src/jattach_windows.c#L92) right before `CreateRemoteThread()`.
