### ISSUE TITLE
Include .pdb files in release

### ISSUE THREAD

**Issue by mitsirak** [apangin/jattach#41]
Can you please include .pdb files along with the executables?

**Comment by apangin** [comment]
What problem is it going to solve?
I mean, the source code is just one C file, and the entire build process is just running cl.exe on it. So, if you'd like to debug the program, you can easily build it yourself, don't you?

**Comment by mitsirak** [comment]
Haven't been able to build in a Windows machine with cl.exe. Is that possible? Can you include the steps required?

**Comment by apangin** [comment]
Here is the command to build jattach with cl.exe:
https://github.com/apangin/jattach/blob/55745c5875fa613081ecbc25b17f0417810f521d/Makefile#L33

Just add `/Zi` to add .pdb

**Comment by mitsirak** [comment]
Thank you, I have managed to build and generate the pdb. However, when using the /Zi flag, the program does not behave correctly and causes the jvm to crash. Any ideas?

**Comment by mitsirak** [comment]
The same behavior occurs when building through visual studio and using the Debug configuration. When using Release configuration everything works fine

**Comment by apangin** [comment]
Yeah, this turned out to be a bug.
I committed the fix.
Now it should work fine when compiling with `/Zi`

**Comment by mitsirak** [comment]
Thank you, it now works
