### ISSUE TITLE
jattach causes JVM crash when compiled with the /guard:cf compiler flag

### ISSUE THREAD

**Issue by mitsirak** [apangin/jattach#42]
I'm trying to compile with the /guard:cf flag as described [here](https://docs.microsoft.com/en-us/cpp/build/reference/guard-enable-control-flow-guard?view=msvc-160), because it is mandatory on our CI environment. The compilation succeeds but when trying to attach to a java process using the generated executable, the JVM crashes.

**Comment by apangin** [comment]
jattach works on Windows by injecting a part of itself into the target JVM process. Therefore, the code being injected must not contain pointers into the host address space. However, when compiling with `/guard:cf`, the compiler inserts runtime checks with such pointers.

I made a special version for you in the [precompiled-entry](https://github.com/apangin/jattach/commits/precompiled-entry) branch. It works around the problem by injecting the precompiled binary snippet instead of the part of itself.

**Comment by mitsirak** [comment]
Thank you very much for looking into this. Sadly I still get the same behavior.

**Comment by apangin** [comment]
I could successfully compile [this version](https://github.com/apangin/jattach/blob/precompiled-entry/src/jattach_windows.c) with `/guard:cf`, and it worked fine.

I think I also provided a reasonable explanation why the original version is not compatible with `/guard:cf`, which should probably serve as enough justification to apply special building policies.

Without extra details, I don't know how to help you further, sorry.

**Comment by mitsirak** [comment]
I have noticed that the issue occurs only when compiling for x86. On x64 it works properly. The error message I get is the following:
```
Connected to remote process
Attach is not supported by the target process (error code = -1073741819)
```
and the JVM crashes.

**Comment by apangin** [comment]
Yes, because the precompiled code was built for x64.
x86 would require different code for `remote_thread_entry`. But x86 JVMs are kind of exotic nowadays.

**Comment by mitsirak** [comment]
In my case x86 JVMs are quite often, because I'm working with legacy systems, x64 and Java 9+ is the exotic thing for me :) . Can the x86 `remote_thread_entry` be added and inserted according to 'bitness'?

**Comment by apangin** [comment]
OK, if I understand correctly, you're asking to adapt jattach software to work with legacy systems, and with your specific build requirements. I could probably help you with that, but would you mind purchasing a consulting service / support contract then?

I mean, this request seems to get a bit beyond the scope of the community project; I'm fine working on that, just want to make sure I'm not working for someone else's business for free. Thank you for understanding. DM me in Twitter or Telegram if interested.

**Comment by apangin** [comment]
Closing the issue in the absense of further interest in that.
