### ISSUE TITLE
No dump file specified

### ISSUE THREAD

**Issue by mahesh-tier1app** [apangin/jattach#46]
Hi, 

I am trying to capture heap dump from the process running inside a docker container but getting a "**No dump file specified**" error message.

I am executing the below command from the host and passing the process id from the host PID namespace.

```sudo ./jattach <PID> dumpheap > heapdump.bin```

**Comment by deadok22** [comment]
Hi @mahesh-tier1app!

In the command you shared, the heap dump file is indeed not specified. 

The `> heapdump.bin` bit is your shell's syntax for redirecting the stdout of the previous command to heapdump.bin, which is not what you want to do here. 

Try adding the file name as the last argument to jattach instead.

**Comment by mahesh-tier1app** [comment]
After going through **dumpheap** command implementation, I realised that I was not passing the file path. Here is the updated command: ```sudo ./jattach <PID> dumpheap hd.bin```.

But the problem is it is writing a file inside the container. Is there any way to write this file in the current directory of host?

**Comment by deadok22** [comment]
There isn't because the jattach process itself is run in the container's mount namespace. 
You're going to have to copy the file from the container to the host. One way to do that would be to run `cp /proc/$pidinhostnamespace/root/$heapdumpPathInContainerNamespace $destinationPathInHostNamespace` in the host mount namespace.

**Comment by mahesh-tier1app** [comment]
Thanks. I will try ```cp``` command. I am able to save "threaddump" command output in a file on the host. This command stdout logs so I am able to redirect it to file. Here is a command ``` sudo ./jattach <PID> threaddump > threaddump.txt```.

**Comment by mahesh-tier1app** [comment]
Hi @deadok22, Thanks. I can copy the heap dump file.
