### ISSUE TITLE
Could not start attach mechanism: No such file or directory

### ISSUE THREAD

**Issue by mahesh-tier1app** [apangin/jattach#47]
I am running a java application inside the container and jattach on the host. The java process id on the host is ```20557```. When I execute the jattach to capture threaddump and heapdump from the host. I get the below errors - 

Thread dump - ```Could not start attach mechanism: No such file or directory```

Heap Dump - 

`com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file /proc/20557/root/tmp/.java_pid20557: target process 20557 doesn't respond within 10500ms or HotSpot VM not loaded
          at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:100)
          at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
          at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
          at jdk.jcmd/sun.tools.jcmd.JCmd.executeCommandForPid(JCmd.java:114)
          at jdk.jcmd/sun.tools.jcmd.JCmd.main(JCmd.java:98)`

I have seen the troubleshooting section in this [link](https://github.com/jvm-profiling-tools/async-profiler#troubleshooting)

1. Attach socket file ```.java_pidNNN``` is not present in ```/tmp``` directory on the host. when I execute ```lsof -p PID | grep java_pid``` it doesn't return any output.
2. I have not started JVM with ```-XX:+DisableAttachMechanism```.
3. Command ```kill -3 PID``` doesn't return anything.

It works if I pass ```-XX:+StartAttachListener``` to JVM but still ```.java_pidNNN``` file is missing in ```/tmp``` directory on the host.

Is there any way to fix this issue without passing ```-XX:+StartAttachListener``` to JVM?

**JDK -** 
openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7-LTS, mixed mode, sharing)

**OS -** 

CentOS Linux release 7.9.2009 (Core)
3.10.0-1160.42.2.el7.x86_64

**Comment by mahesh-tier1app** [comment]
I think I am using the latest version. When I execute ```./jattach -version``` it returns **jattach 2.0 built on Aug 11 2021**

I executed ```kill -3 pid``` on a host. Is that correct? Or do I need to execute inside a container where the java application is running?

We are using jattach in our go script. When we run the go script on the host it executes jattach commands to capture GC log, thread dump, and heap dump. I think something is wrong with the go script. Because if I directly run jattach on the host then I am able to capture data from the process running inside a container.

**Comment by mahesh-tier1app** [comment]
When I execute the ```sudo ./jattach <PID> threaddump > threaddump.txt``` on host, it creates socket file ```.java_pid1``` inside ```/proc/<PID>/root/tmp``` directory. The java process running inside container has PID 1 within container.

But when I execute go script from the host, it is not creating a socket file inside ```/tmp```.

**Comment by apangin** [comment]
> I think something is wrong with the go script. Because if I directly run jattach on the host then I am able to capture data from the process running inside a container.

Looks like it. 

> Is it correct to say, when the target JVM is launched with -XX:+StartAttachListener then socket file is not needed?

Not exactly. `-XX:+StartAttachListener` forces JVM to create an attach socket from the very beginning (at JVM startup), so that jattach can use it right away.

**Comment by mahesh-tier1app** [comment]
I will close this ticket since the issue is within the go script and not with the jattach tool.

> -XX:+StartAttachListener forces JVM to create an attach socket from the very beginning (at JVM startup), so that jattach can use it right away.

You are right! I have validated it. I launched a target JVM inside a container with ```-XX:+StartAttachListener```. When I went to ```/proc/<PID_FROM_HOST>/root/tmp``` directory on the host filesystem, I found ```.java_pid8```. The java process inside the container has PID 8.

I have some doubts. I know it's not related to the original question. But I would appreciate it if you can clarify.

Where the ```.attach_pid<PID>``` file will be located? and will it get created when we launch the JVM or when the first request occurs?

Thanks for your help.

**Comment by apangin** [comment]
> Where the .attach_pid<PID> file will be located? and will it get created when we launch the JVM or when the first request occurs?

`.attach_pid` is a marker file that tells JVM to start attach mechanism and to open `.java_pid` socket. Once the socket is opened, the marker file is removed. Also, it's not created at all if JVM runs with `-XX:+StartAttachListener`.

A client (jattach or jstack, jmap, etc.) first tries to create `.attach_pid` in the current working directory of the target JVM process. If there are not enough permissions to create a file in the working directory, `.attach_pid` is created in `/tmp` of the container.

**Comment by mahesh-tier1app** [comment]
Thank you for giving me this information.
