### ISSUE TITLE
Run jattach without sudo

### ISSUE THREAD

**Issue by mahesh-tier1app** [apangin/jattach#51]
Hi,

I have embedded jattach into my go script. When I run my go script from host to capture GC log, thread dump, and heap dump from the java application running inside the Docker container I get ```Failed to change credentials to match the target process: Operation not permitted``` error message. But if I run my go script with ```sudo``` it works fine.

I am using a service account. Can you help me with figuring out what priviledges are required to access the monitoring information rather than using ```sudo```?

Thanks :)

**Comment by apangin** [comment]
To attach to a running JVM, a user must have exactly the same effective uid/gid as the target process. This is a limitation of the JVM, not of jattach.

If credentials do not match, jattach automatically tries to change them with [`seteuid` / `setegid`](https://man7.org/linux/man-pages/man2/setegid.2.html) calls. This is allowed to a privileged account only - typically `root`, or, more precisely, an account with `CAP_SETUID` and `CAP_SETGID` [capabilities](https://man7.org/linux/man-pages/man7/capabilities.7.html).

**Comment by mahesh-tier1app** [comment]
> To attach to a running JVM, a user must have exactly the same effective uid/gid as the target process. This is a limitation of the JVM, not of jattach.

So you meant to say uid/gid of the user who is running java process inside a container and the user who is executing jattach from the host should match. Am I right?

**Comment by apangin** [comment]
> uid/gid of the user who is running the java process inside a container and the user who is executing jattach from the host should match. Am I right?

Yes

**Comment by mahesh-tier1app** [comment]
Thank you @apangin. I am closing this issue for now.
