### ISSUE TITLE
Capture GC log using jattach

### ISSUE THREAD

**Issue by mahesh-tier1app** [apangin/jattach#53]
Hi,

I am running one java application without turning on the GC logging. I cannot use ```jstat``` because I don't JDK. When I used ```jattach <PID> jcmd GC.class_stats > gc.log``` command, it returns data but as per my understanding, I think that is not a valid GC log format.

Is there any other way to capture a GC log from the running application?

**Comment by apangin** [comment]
I'm not sure what you mean by "capture GC log".
`jattach` does not implement any monitoring functionality itself; it only invokes diagnostic commands that the target JVM provides.

**Comment by mahesh-tier1app** [comment]
Thanks for your reply. I meant to say how can I collect garbage collection-related information from the target JVM. We can get GC information using the ```jstat``` tool. For example ```jstat -gc -t <PROCESS_ID> 10000 30```. Similar to this is there any way to get GC information using ```jattach```?

**Comment by apangin** [comment]
This question has been already answered in #36

**Comment by mahesh-tier1app** [comment]
Thank you @apangin
