### ISSUE TITLE
Example to Dump Heap on Remote Machine

### ISSUE THREAD

**Issue by k4kpk** [apangin/jattach#55]
I'd like to dump the heap of a process 1234 running on a remote JVM which is on a host named "myhost".  How do I specify the host name in the jattach command line?

I see, "The utility to send commands to remote JVM via Dynamic Attach mechanism," but I don't see any arguments to specify the name of the remote host.   Does "remote JVM" mean something less than "JVM running on another host?"

**Comment by apangin** [comment]
"remote" here means the remote process, not the remote host.
I've reworded the confusing statement.

To manage the JVM on a remote machine, use JMX.
