### ISSUE TITLE
Whether to support perf-map-agent in different containers？

### ISSUE THREAD

**Issue by arrowfeng** [apangin/jattach#58]
hello, recently I'm researching how to use [perf-map-agent ](https://github.com/jvm-profiling-tools/perf-map-agent)in different containers, the program uses "java cp", does jattach support it?

**Comment by apangin** [comment]
If I understand the question correctly, you want to attach the agent to a JVM running in a different container.
Yes, `jattach` does that. But the agent library must be accessible from the container you attach to. E.g. if the agent is located at `/some/path/libperfmap.so`, the same path must exist in the target container, too.

For profiling Java applications in a container, I'd recommend [async-profiler](https://github.com/jvm-profiling-tools/async-profiler) (I'm the author and therefore biased). async-profiler [supports containers](https://github.com/jvm-profiling-tools/async-profiler#profiling-java-in-a-container), it can be used both inside a container and on the host. In either case, the profiler library should be accessible inside a container.

**Comment by arrowfeng** [comment]
Thanks for your reply, async-profiler looks like a good thing, I researched it. Also, I'm still wondering how I can use jattach to load the jar and execute it? For example this command 'java -cp xxx.jar:$JAVA_HOME/tools.jar com.xx.Net 123'

**Comment by arrowfeng** [comment]
I know how to use jattach, but it didn't work what i want. 
Let me briefly describe my usage scenario. I have a Pod with two containers that share the Pid namespace. One of the containers A runs a JAVA application, while the other container B uses jattach to load a module and finds an error, but uses attach to load a module in container A is normal. When I mount the /tmp directory of container A to container B, jattach is normal, I am curious what happened? How jattach attaches jvm between containers？

**Comment by apangin** [comment]
> how I can use jattach to load the jar and execute it?

`jattach` invokes a diagnostic command on the *existing JVM*. You need a running Java process to attach to. Launching a new JVM is not a job of `jattach`.

Do you probably mean [`docker exec`](https://docs.docker.com/engine/reference/commandline/exec/)?

**Comment by apangin** [comment]
> When I mount the /tmp directory of container A to container B, jattach is normal, I am curious what happened? How jattach attaches jvm between containers?

The overview of how dynamic attach works is [here](https://stackoverflow.com/questions/26140182/running-jmap-getting-unable-to-open-socket-file/35963059#35963059).
A socket for communication with the target JVM is created in `/tmp`, so `/tmp` indeed should be shared between containers.

Alternatively, if you run `jattach` by a privileged user, the tool automatically switches to the target `pid` and `mnt` namespaces.

**Comment by arrowfeng** [comment]
thanks, i'm work well.
