### ISSUE TITLE
JVM did not respond: Resource temporarily unavailable

### ISSUE THREAD

**Issue by mahesh-tier1app** [apangin/jattach#60]
Hello,

I am getting ```JVM did not respond: Resource temporarily unavailable``` error message when I run ```jattach <PID> jcmd GC.heap_dump``` command a second time. Does it mean JVM was very sick and couldn't respond?

**Comment by apangin** [comment]
The error message means that `jattach` created a socket for communication, but JVM did not connect to it in time.
The reasons can be different: e.g. JVM process got stuck, or it has no permission to connect.

**Comment by mahesh-tier1app** [comment]
Thanks for your reply. I am also getting the below error. Do you think its because of the above same reasons? 

```
Connected to remote JVM
Error reading response: Resource temporarily unavailable
```

**Comment by apangin** [comment]
The latter error means the connection with the JVM has been established, but `jattach` has not received the response from OpenJ9 in 5 seconds. There may be cases when the JVM takes more time to respond, so I removed this timeout.

**Comment by mahesh-tier1app** [comment]
Hi @apangin Thanks for your help. I will test again. When are you planning to release a new version?

**Comment by mahesh-tier1app** [comment]
Is there a DEBUG log for jattach to get more details?

**Comment by apangin** [comment]
> When are you planning to release a new version?

I have no particular plans.
You can easily build the binary yourself - it's just a matter of a singe `make` command.

> Is there a DEBUG log for jattach to get more details?

No, there are hardly many details to be logger. `jattach` already checks the error condition after every step.

**Comment by mahesh-tier1app** [comment]
Thank you :)
