### ISSUE TITLE
jcmd in IBM java 8 OpenJ9

### ISSUE THREAD

**Issue by mahesh-tier1app** [apangin/jattach#61]
Hi,

I am using IBM java 8 and trying to use jattach to get the output of ```VM.system_properties```, ```VM.flags```, ```GC.heap_info``` options.

```
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 8.0.7.6 - pxa6480sr7fp6-20220330_01(SR7 FP6))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220303_23850 (JIT enabled, AOT enabled)
OpenJ9   - 6890476
OMR      - 1e70123
IBM      - 1b0232b)
JCL - 20220120_01 based on Oracle jdk8u321-b07
```
But I don't see these options in the list when I run ```jattach <PID> jcmd help```.

```
Connected to remote JVM
Dump.heap
Dump.java
Dump.snap
Dump.system
GC.class_histogram
GC.heap_dump
GC.run
Thread.print
help
jstat.class

```

Any idea how can I run these options using jattach?

**Comment by apangin** [comment]
You can't. OpenJ9 VM does not support these jcommands. `jcmd help` shows the complete list of supported commands.

**Comment by apangin** [comment]
Correction: in fact, there is a replacement for `VM.system_properties`:
```
jattach <PID> properties
```
but not for `VM.flags` or `GC.heap_info`

**Comment by mahesh-tier1app** [comment]
Thanks @apangin
