### ISSUE TITLE
ARM unable to use jattach.

### ISSUE THREAD

**Issue by Nizernizer** [apangin/jattach#62]
After testing, ARM(Advanced RISC Machine) unable to use jattach.

**Comment by apangin** [comment]
jattach is known to work both on ARM32 and ARM64.
How do you build it, run it, and what exact error do you get?

**Comment by apangin** [comment]
The binary on that page is only for Linux-x64.
For Linux-ARM, you need to build it yourself. It's simple - just a matter of a single `make` command (assuming `gcc` and `make` are already installed).
Alternatively, you can get an existing linux-arm64 build of [async-profiler](https://github.com/jvm-profiling-tools/async-profiler/releases) - the package includes jattach inside.
