### ISSUE TITLE
Attach is not supported by the target process (error code = 100)

### ISSUE THREAD

**Issue by teaserofta** [apangin/jattach#63]
`.\jattach.exe 6884 load instrument false "agent.jar=arguments"`

`Connected to remote process
Attach is not supported by the target process (error code = 100)`

how would I fix this? and what is the cause?

**Comment by teaserofta** [comment]
```
PS C:\Users\User\AppData\Local\Temp> .\jattach1490831287247899151.exe 6116 load instrument false "F:\untitled\out\artifacts\agent_jar\agent.jar=arguments"
Connected to remote process
Attach is not supported by the target process (error code = 100)
```

**Comment by teaserofta** [comment]
it doesnt seem like theres anything in the jvm logs

**Comment by apangin** [comment]
Ah, I see.
`error code = 100` means that the attach has been disabled in the target JVM: perhaps, the Java process has been started with `-XX:+DisableAttachMechanism` option.

**Comment by apangin** [comment]
This is an expected behavior if attach is intentionally disabled on the JVM side; closing the issue.
