### ISSUE TITLE
Process's guid changed after attach operation using jattach as library in linux

### ISSUE THREAD

**Issue by yoshichino** [apangin/jattach#66]
using jattach as library should not change process's guid in any situation. 
```c++
    // In HotSpot, dynamic attach is allowed only for the clients with the same euid/egid.
    // If we are running under root, switch to the required euid/egid automatically.
    if ((my_gid != target_gid && setegid(target_gid) != 0) ||
        (my_uid != target_uid && seteuid(target_uid) != 0)) {
        perror("Failed to change credentials to match the target process");
        return 1;
    }
```
I think can fork a sub process change guid and do attach.
In platform windows when attach as administrators it don't change my process user to tomcat.
This feature in linux will be confusion when I ues jattach as library.

**Comment by apangin** [comment]
This is the intended behavior.
Any necessary forking should be done before calling jattach.
