### ISSUE TITLE
Support ARM64

### ISSUE THREAD

**Issue by spockz** [apangin/jattach#67]
As ARM64 devices (primarily through Apple Silicon) are becoming prevalent it would be nice if there would be a native arm64 build available as well. On macOS Rosetta works good enough, but for containers on macOS a native arm64 binary is preferred as it gives less dependencies on having the docker host "properly" installed and configured with qemu.

I cannot find the way how releases are made in the repository itself, otherwise I would have created a PR myself.

**Comment by apangin** [comment]
jattach natively supports Apple Silicon since [release 2.0](https://github.com/apangin/jattach/releases/tag/v2.0)

**Comment by jumarko** [comment]
@apangin We are using Amazon Linux VMs running on ARM ec2 instances for our container workloads 
and it seems attach isn't working anymore - before we used it on x86 instances and it worked fine.

```
uname -a
Linux ip-10-0-1-205.eu-west-1.compute.internal 4.14.305-227.531.amzn2.aarch64 #1 SMP Tue Feb 14 09:55:25 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

/usr/local/bin/jattach
bash: /usr/local/bin/jattach: cannot execute binary file: Exec format error
```

Our installation procedure is just this (in Dockerfile):
```
RUN wget https://github.com/apangin/jattach/releases/download/v2.0/jattach -O /usr/local/bin/jattach && chmod +x /usr/local/bin/jattach
```

**Comment by apangin** [comment]
@jumarko Seems like you're launching x86 binary on ARM hardware. macOS has multi-arch binaries, but Linux doesn't - you need to build a separate binary for ARM.

**Comment by apangin** [comment]
@jumarko Yes, building is as simple as running `make` (with no arguments)
